name: cd
on:
  push:
    branches: [main]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: "europe-north1"
  GAR_REPOSITORY: "notely-ar-repo"
  IMAGE_NAME: "wuggyx2/notely"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Submit build to Google Cloud Build
        run: |
          # Construct the full image paths for tagging
          IMAGE_PATH_BASE="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}"
          
          IMAGE_TAG_SHA="${IMAGE_PATH_BASE}:${{ github.sha }}"
          IMAGE_TAG_LATEST="${IMAGE_PATH_BASE}:latest"

          echo "Submitting build to Google Cloud Build..."
          echo "Image will be tagged as: $IMAGE_TAG_SHA"
          echo "And as: $IMAGE_TAG_LATEST"

          gcloud builds submit \
            --project=${{ env.GCP_PROJECT_ID }} \
            --tag "$IMAGE_TAG_SHA" \
            --tag "$IMAGE_TAG_LATEST" \
            .  
      - name: Deploy to Cloud Run
        run: |
          IMAGE_PATH="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest"
          gcloud run deploy notely --image "$IMAGE_PATH" --region "${{env.GAR_LOCATION}}" --allow-unauthenticated --project "${{env.GCP_PROJECT_ID}}" --max-instances=4
